language: R
sudo: required
dist: bionic
cache: packages

addons:
  apt:
    update: true
    sources:
      - sourceline: 'ppa:opencpu/jq'
      - sourceline: 'ppa:ubuntugis/ubuntugis-unstable'
    packages:
      - libproj-dev
      - libudunits2-dev
      - libv8-dev
      - libprotobuf-dev
      - libprotoc-dev
      - protobuf-compiler
      - valgrind
      - libjq-dev
      - python-numpy
      - aria2
      - netcdf-bin
      - gdal-bin
      - python-gdal

install:
  - wget https://github.com/libgeos/geos/archive/3.7.1.tar.gz
  - tar -xzvf 3.7.1.tar.gz
  - pushd geos-3.7.1 && ./autogen.sh && mkdir obj && cd obj && ../configure
  - make && sudo make install
  - cd ../../
  - wget https://github.com/OSGeo/gdal/archive/v2.2.3.tar.gz
  - tar -xzvf v2.2.3.tar.gz
  - pushd gdal-2.2.3/gdal && ./configure
  - make && sudo make install
  - cd ../../

r:
  - release
  - devel
  - oldrel

r_packages:
  - RPostgreSQL
  - covr

before_script:
  - mkdir $HOME/.sen2r
  - echo "user user" > $HOME/.sen2r/apihub.txt
  
script: 
  - R CMD build .
  - travis_wait 120 R CMD check *tar.gz

env:
  global:
    - R_LIBS="http://cran.rstudio.com"
    - R_BUILD_ARGS="--no-build-vignettes --no-manual"
    - R_CHECK_ARGS="--no-build-vignettes --no-manual --as-cran"
    - R_CHECK_TIMINGS_="0"

notifications:
  email:
    on_success: change
    on_failure: change

