language: R
sudo: required
dist: bionic
cache: packages

addons:
  apt:
    update: true
    sources:
      - sourceline: 'ppa:opencpu/jq'
      - sourceline: 'ppa:ubuntugis/ubuntugis-unstable'
    packages:
      - libudunits2-dev
      - libv8-dev
      - libprotobuf-dev
      - libprotoc-dev
      - protobuf-compiler
      - valgrind
      - libjq-dev
      - python-numpy
      - aria2
      - netcdf-bin
      - gdal-bin
      - python-gdal

before_install:
  - export LD_LIBRARY_PATH="$LD_LIBRARY_PATH:/usr/local/lib"
  - export PATH="$PATH:/usr/local/bin"
  - wget https://github.com/libgeos/geos/archive/3.6.2.tar.gz
  - tar -xzvf 3.6.2.tar.gz &> /tmp/build.log
  - pushd geos-3.6.2 && ./autogen.sh
  - mkdir obj && cd obj
  - ../configure &> /tmp/build.log
  - make &> /tmp/build.log
  - sudo make install &> /tmp/build.log
  - cd ../../
  - wget https://github.com/OSGeo/PROJ/archive/4.9.3.tar.gz
  - tar -xzvf 4.9.3.tar.gz &> /tmp/build.log
  - pushd PROJ-4.9.3 && ./autogen.sh 
  - mkdir obj && cd obj 
  - ../configure &> /tmp/build.log
  - travis_wait 50 sh -c 'make &> /tmp/build.log'
  - travis_wait 50 sudo sh -c 'make install &> /tmp/build.log'
  - cd ../../
  - wget https://github.com/OSGeo/gdal/archive/v2.2.3.tar.gz
  - tar -xzvf v2.2.3.tar.gz &> /tmp/build.log
  - pushd gdal-2.2.3/gdal
  - ./configure &> /tmp/build.log
  - travis_wait 50 sh -c 'make &> /tmp/build.log'
  - travis_wait 50 sudo sh -c 'make install &> /tmp/build.log'
  - cd ../../
  - Rscript -e 'install.packages(c("sf", "rgdal"), configure.args = c("--with-gdal-config=/usr/local/bin/gdal-config", "--with-proj-lib=/usr/local/lib/"))'

r:
  - release
  - devel
  - oldrel

r_packages:
  - RPostgreSQL
  - covr

before_script:
  - mkdir $HOME/.sen2r
  - echo "user user" > $HOME/.sen2r/apihub.txt
  
script: 
  - R CMD build .
  - travis_wait 120 R CMD check *tar.gz

env:
  global:
    - R_LIBS="http://cran.rstudio.com"
    - R_BUILD_ARGS="--no-build-vignettes --no-manual"
    - R_CHECK_ARGS="--no-build-vignettes --no-manual --as-cran"
    - R_CHECK_TIMINGS_="0"

notifications:
  email:
    on_success: change
    on_failure: change
