language: R
sudo: required
dist: bionic
cache: packages

import:
  source: libgeos/geos:.travis.yml@master
  
addons:
  apt:
    update: true
    sources:
      - sourceline: 'ppa:opencpu/jq'
      - sourceline: 'ppa:ubuntugis/ubuntugis-unstable'
    packages:
      - libgdal-dev
      - libproj-dev
      - libudunits2-dev
      - libv8-dev
      - libprotobuf-dev
      - libprotoc-dev
      - protobuf-compiler
      - valgrind
      - libjq-dev
      - python-numpy
      - python-gdal
      - aria2
      - netcdf-bin
      - gdal-bin
      - python-gdal

r:
  - release
  - devel
  - oldrel

r_packages:
  - RPostgreSQL
  - covr

before_script:
  - mkdir $HOME/.sen2r
  - echo "user user" > $HOME/.sen2r/apihub.txt
  
script: 
  - R CMD build .
  - travis_wait 120 R CMD check *tar.gz

env:
  global:
    - R_LIBS="http://cran.rstudio.com"
    - R_BUILD_ARGS="--no-build-vignettes --no-manual"
    - R_CHECK_ARGS="--no-build-vignettes --no-manual --as-cran"
    - R_CHECK_TIMINGS_="0"

notifications:
  email:
    on_success: change
    on_failure: change

