language: R
sudo: required
dist: bionic
cache: packages

addons:
  apt:
    update: true
    sources:
      - sourceline: 'ppa:opencpu/jq'
      - sourceline: 'ppa:ubuntugis/ubuntugis-unstable'
    packages:
      - libudunits2-dev
      - libv8-dev
      - libprotobuf-dev
      - libprotoc-dev
      - protobuf-compiler
      - valgrind
      - libjq-dev
      - python-numpy
      - aria2
      - netcdf-bin
      - gdal-bin
      - python-gdal
      - libproj-dev
      - libmysqlclient-dev
      - libarmadillo-dev
      - libc6-dev
      - libcurl4-gnutls-dev
      - libdap-dev
      - libepsilon-dev
      - libexpat1-dev
      - libfreexl-dev
      - libfyba-dev
      - libgeotiff-dev
      - libgif-dev
      - libhdf4-alt-dev
      - libhdf5-dev
      - libjpeg-dev
      - libjson-c-dev
      - libkml-dev
      - libltdl-dev
      - liblzma-dev
      - libnetcdf-dev
      - libogdi3.2-dev
      - libopenjp2-7-dev
      - libpcre3-dev
      - libpng-dev
      - libpoppler-private-dev
      - libpq-dev
      - libqhull-dev
      - libspatialite-dev
      - libsqlite3-dev
      - libtiff-dev
      - liburiparser-dev
      - libwebp-dev
      - libxerces-c-dev
      - libxml2-dev
      - unixodbc-dev
before_install:
  - export LD_LIBRARY_PATH="$LD_LIBRARY_PATH:/usr/local/lib"
  - export PATH="$PATH:/usr/local/bin"
  - wget https://github.com/libgeos/geos/archive/3.6.2.tar.gz
  - tar -xzvf 3.6.2.tar.gz > /tmp/build1.log
  - pushd geos-3.6.2 && ./autogen.sh
  - mkdir obj && cd obj
  - ../configure
  - make &> /tmp/build3.log
  - sudo make install
  - cd ../../
  - wget https://github.com/OSGeo/gdal/archive/v2.2.3.tar.gz
  - tar -xzvf v2.2.3.tar.gz > /tmp/build9.log
  - pushd gdal-2.2.3/gdal
  - ./configure --with-netcdf --with-libtiff --with-sqlite3 --with-geotiff --with-mysql --with-curl --with-perl --with-geos --with-png --with-poppler --with-spatialite --with-openjpeg
  - travis_wait 50 sh -c 'make > /tmp/build11.log'
  - make install
  - cd ../../
  - Rscript -e 'install.packages(c("sf", "rgdal"), configure.args = "--with-gdal-config=/usr/local/bin/gdal-config --with-geos-config=/usr/local/bin/geos-config --with-proj-include=/usr/local/include/ --with-proj-lib=/usr/local/lib/")'

r:
  - release
  - devel
  - oldrel

r_packages:
  - RPostgreSQL
  - covr

before_script:
  - mkdir $HOME/.sen2r
  - echo "user user" > $HOME/.sen2r/apihub.txt
  
script: 
  - R CMD build .
  - travis_wait 50 R CMD check *tar.gz

env:
  global:
    - R_LIBS="http://cran.rstudio.com"
    - R_BUILD_ARGS="--no-build-vignettes --no-manual"
    - R_CHECK_ARGS="--no-build-vignettes --no-manual --as-cran"
    - R_CHECK_TIMINGS_="0"

notifications:
  email:
    on_success: change
    on_failure: change
