# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: required
dist: trusty
cache: packages
r_github_packages: lbusett/sprawl

before_install:
  - sudo add-apt-repository ppa:ubuntugis/ubuntugis-unstable --yes
  - sudo apt-get -qq update
  - sudo apt-get install -y libgdal-dev libproj-dev libv8-dev protobuf-compiler

matrix:
  include:
    - os: linux
      dist: trusty
      env:
      global:
      - R_BUILD_ARGS=" "
      - R_CHECK_ARGS="--no-build-vignettes --no-manual --timings"
      - R_CHECK_TIMINGS_="0"
      addons:
        apt:
          packages:
            - libgdal-dev
            - libproj-dev
            - units
            - libudunits2-dev
            - libv8-dev
            - protobuf-compiler
